### ISSUE TITLE
le test en local ubuntu 14.4

### ISSUE THREAD

**Issue by alainbron** [JamesRezo/spip_svn_loader#5]
Bonsoir,

La liste des erreurs recues option "maintenance"  avec la dernière version : j'ai mis les dernières lignes qui me semblent ok : 
   A ecrire/public/composer.php
   A ecrire/public/admin.php
   A ecrire/public/phraser_html.php
   C local
   A local/remove.txt
   C htaccess.txt
   C IMG
   A IMG/remove.txt
   C index.php
   C spip.png
 U   .

Récupération de la référence externe dans 'squelettes-dist' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/squelettes-dist'

Récupération de la référence externe dans 'plugins-dist/breves' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/breves'

Récupération de la référence externe dans 'plugins-dist/jquery_ui' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/jquery_ui'

Récupération de la référence externe dans 'plugins-dist/compagnon' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/compagnon'

Récupération de la référence externe dans 'plugins-dist/compresseur' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/compresseur'

Récupération de la référence externe dans 'plugins-dist/dump' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/dump'

Récupération de la référence externe dans 'plugins-dist/filtres_images' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/filtres_images'

Récupération de la référence externe dans 'plugins-dist/forum' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/forum'

Récupération de la référence externe dans 'plugins-dist/mediabox' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/mediabox'

Récupération de la référence externe dans 'plugins-dist/medias' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/medias'

Récupération de la référence externe dans 'plugins-dist/mots' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/mots'

Récupération de la référence externe dans 'plugins-dist/organiseur' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/organiseur'

Récupération de la référence externe dans 'plugins-dist/petitions' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/petitions'

Récupération de la référence externe dans 'plugins-dist/plan' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/plan'

Récupération de la référence externe dans 'plugins-dist/porte_plume' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/porte_plume'

Récupération de la référence externe dans 'plugins-dist/revisions' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/revisions'

Récupération de la référence externe dans 'plugins-dist/safehtml' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/safehtml'

Récupération de la référence externe dans 'plugins-dist/sites' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/sites'

Récupération de la référence externe dans 'plugins-dist/squelettes_par_rubrique' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/squelettes_par_rubrique'

Récupération de la référence externe dans 'plugins-dist/statistiques' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/statistiques'

Récupération de la référence externe dans 'plugins-dist/svp' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/svp'

Récupération de la référence externe dans 'plugins-dist/textwheel' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/textwheel'

Récupération de la référence externe dans 'plugins-dist/urls_etendues' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/urls_etendues'

Récupération de la référence externe dans 'plugins-dist/vertebres' :
svn: avertissement W155007 : Impossible de verrouiller le non-répertoire '/var/www/html/plugins-dist/vertebres'

Révision 22930 extraite.
Arborescences en conflit sur 'COPYING.txt'
    > local file unversioned, incoming file add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'COPYING.txt' résolu
Arborescences en conflit sur 'IMG'
    > local dir unversioned, incoming dir add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'IMG' résolu
Arborescences en conflit sur 'INSTALL.txt'
    > local file unversioned, incoming file add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'INSTALL.txt' résolu
Arborescences en conflit sur 'config'
    > local dir unversioned, incoming dir add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'config' résolu
Arborescences en conflit sur 'ecrire'
    > local dir unversioned, incoming dir add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'ecrire' résolu
Arborescences en conflit sur 'htaccess.txt'
    > local file unversioned, incoming file add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'htaccess.txt' résolu
Arborescences en conflit sur 'index.php'
    > local file unversioned, incoming file add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'index.php' résolu
Arborescences en conflit sur 'local'
    > local dir unversioned, incoming dir add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'local' résolu
Arborescences en conflit sur 'prive'
    > local dir unversioned, incoming dir add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'prive' résolu
Arborescences en conflit sur 'spip.php'
    > local file unversioned, incoming file add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'spip.php' résolu
Arborescences en conflit sur 'spip.png'
    > local file unversioned, incoming file add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'spip.png' résolu
Arborescences en conflit sur 'tmp'
    > local dir unversioned, incoming dir add upon update
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Conflit sur 'tmp' résolu

Merci bien Alain

**Comment by JamesRezo** [comment]
Les erreurs produites pas les commandes `svn` ne sont pas cachées, effectivement. Je vais essayer de reproduire.

**Comment by JamesRezo** [comment]
Pour reproduire, j'ai fait une installation sans svn, puis j'ai installé dessus avec le script une release attachée à SVN. J'obtiens les mêmes erreurs et c'est lié, entre autres, à des conflits de propriétés svn (`svn:mergeinfo` et `svn:externals`, etc.).

Pour corriger, j'ai nettoyer avec la suite de commandes ci-dessous :

``` bash
zip -r spip.zip plugins config IMG -x config/ecran_securite.php config/remove.txt IMG/remove.txt && mv spip.zip squelettes
svn cleanup --remove-unversioned --include-externals && svn revert -R . && svn up
mv squelettes/spip.zip . && unzip spip.zip && rm spip.zip
```

Et après, ça va mieux.

Il faudrait éventuellement améliorer le script pour qu'il propose cette méthode quand il rencontre ce type d'erreur. Cela signifie, s'assurer que zip/unzip sont utilisables et que la liste des fichiers à sauver est suffisantes et gérer correctement les "erreurs" produites par `svn`.
